### ISSUE TITLE
404 Error on Whence Blob

### ISSUE THREAD

**Issue by F9Alejandro** [qzed/aarch64-arch-mkimg#6]
Expected:
- Download succeeds 

Current:
- error: failed retrieving file 'linux-firmware-msft-surface-pro-x-whence-20220509.b19cbdc-1-any.pkg.tar.zst' from pkg.surfacelinux.com : The requested URL returned error: 404

Looks like it is not getting the blob and instead is trying to get the .zst based instead.

Please look and see if this is the case as it has issues trying to grab.

**Comment by qzed** [comment]
Thanks for reporting this! It should be fixed now.

It looks like one of the automated cleanups (https://github.com/linux-surface/repo/commit/d54c103a2bbccf3de9c68224e4b6309f4b91de74) removed the blob file. This seems to have happened because downloading the file failed for some reason, which causes the update/cleanup script to assume that the file is no longer available on the GitHub release page and thus no longer needed. I'm not sure why downloading failed (the file is still on the release page), but we've had similar download failures in #5 (only this time not in the mkimage CI but for the first time in the repo action).

I've re-added the missing blob file, which should fix the issue on the repo side. Further, I've also triggered a new build of the firmware package, which then hopefully fixes the intermittent download issues.

Edit: I messed up the repo-surgery, still working on it...

**Comment by qzed** [comment]
Things should work now.

**Comment by F9Alejandro** [comment]
I will pull and test it out. Should also see about getting a faster mirror for ALARM repos instead of relying on archlinuxarm limited mirrors. 

**Depending on the cost could go through linode and create a bunch of nanodes (cheapest tier) in different datacenter locations.**

**Comment by qzed** [comment]
> Depending on the cost could go through linode and create a bunch of nanodes (cheapest tier) in different datacenter locations.

I really don't think that would be worth it. Or help much, for that matter. There are like 10 people (probably even less...) using the SPX. And you need to run the mkimage utility once every time you want to install linux. With automated builds working that probably drops (or increases...) to maybe once a month that this thing is being run.

As for our linux-surface repos in general: We just redirect to GitHub releases for all the heavy downloads, which saves us that burden.

**Comment by F9Alejandro** [comment]
I meant for archlinuxarm in general not for the project itself. The mirrors take forever to actually pull properly and when they do it is abysmal download speeds (kb/s instead of Mb/s). 

Either way this is working properly now :D

Edit: I will work on trying out using the command line option for pacman and see if that will help with the "download speed" issue. It should ignore the default 10 sec timeout from curl when in use.

**Comment by F9Alejandro** [comment]
Hit or miss with the archlinuxarm mirrors. Not much can be done about that unless we grab them directly then install with pacman.
